name: Idea or request
description: Something resumezip could do, or do better.
labels: ["feature"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: How would it help you?
