import { readFileSync } from "node:fs"
import { expect, test, type Page } from "@playwright/test"
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs"
import { pageErrors, seriousAccessibilityProblems } from "./helpers"

const initial = { id: "flexible", resumeTitle: "Flexible", selectedTemplate: "jake", profileSection: { fullName: "Ada Lovelace" }, workExperienceSection: [{ id: 1, workRole: "Engineer", companyName: "Computing", workDescription: "• Built the analytical engine" }] }
const saved = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem("resume:flexible") ?? "{}"))
const nav = (page: Page) => page.getByRole("navigation", { name: "Sections" })
const preview = (page: Page) => page.getByRole("region", { name: "Live preview" })
const previewShown = (page: Page) => expect(preview(page).locator(".react-pdf__Page__canvas").first()).toBeVisible()
async function open(page: Page) {
  await page.addInitScript((resume) => { if (!localStorage.getItem("resume:flexible")) localStorage.setItem("resume:flexible", JSON.stringify(resume)) }, initial)
  await page.goto("/create/new/flexible")
}
async function add(page: Page, kind: string) {
  await nav(page).getByRole("button", { name: "Add section", exact: true }).click()
  await nav(page).getByRole("button", { name: `Add ${kind} section`, exact: true }).click()
}
async function rename(page: Page, heading: string) {
  await page.getByRole("button", { name: "Rename section", exact: true }).click()
  await page.getByRole("textbox", { name: "Section title" }).fill(heading)
  await page.getByRole("textbox", { name: "Section title" }).press("Enter")
}

test("optional section lifecycle, duplicate headings, keyboard movement and v2 PDF reopening", async ({ page, browser }, info) => {
  const errors = pageErrors(page)
  await open(page)
  await previewShown(page)
  await add(page, "Summary")
  await page.getByRole("textbox", { name: "Text", exact: true }).fill("A precise summary.\n\n○ Literal prose.")
  await nav(page).getByRole("button", { name: "Add section", exact: true }).click()
  await expect(nav(page).getByRole("button", { name: "Add Summary section", exact: true })).toBeDisabled()
  await nav(page).getByRole("button", { name: "Add section", exact: true }).click()
  await add(page, "Text")
  await rename(page, "Experience")
  await page.getByRole("textbox", { name: "Text", exact: true }).fill("Community projects and interests.")
  await add(page, "Bullet list")
  await rename(page, "Experience")
  await page.getByRole("textbox", { name: "Bullet points", exact: true }).fill("• **Public** list item\n○ PRIVATE_SENTINEL\n• Final list item")
  await expect(nav(page).getByRole("button", { name: /^\d+ Experience, section \d+$/ })).toHaveCount(3)
  const moving = nav(page).getByRole("button", { name: /^Move Experience, section \d+ section up$/ })
  await moving.focus(); await page.keyboard.press("Enter")
  await expect(moving).toBeFocused()
  await expect(nav(page).getByRole("status")).toContainText("Moved Experience")
  await add(page, "Certifications")
  await page.getByRole("button", { name: "Add credential", exact: true }).click()
  await page.getByLabel("Credential name", { exact: true }).fill("Certified Engineer")
  await page.getByLabel("Issuer", { exact: true }).fill("Institute")
  await page.getByLabel("Issued", { exact: true }).fill("2026")
  await page.getByLabel("Credential ID", { exact: true }).fill("ABC123")
  await page.getByLabel("Link", { exact: true }).fill("https://example.com/credential")
  await page.getByRole("button", { name: "Add credential", exact: true }).click()
  await page.getByLabel("Credential name", { exact: true }).fill("PRIVATE_CREDENTIAL")
  await page.getByRole("checkbox", { name: "Include credential 2 in the PDF", exact: true }).uncheck()
  await expect.poll(async () => (await saved(page)).extraSections?.certifications?.entries?.length).toBe(2)
  await nav(page).getByRole("button", { name: /^\d+ Summary$/ }).click()
  expect(await seriousAccessibilityProblems(page, [".react-pdf__Page"])).toEqual([])
  await page.screenshot({ path: info.outputPath("flexible-editor.png"), fullPage: true })
  const downloading = page.waitForEvent("download")
  await page.getByRole("button", { name: "Download PDF", exact: true }).click()
  const file = info.outputPath("flexible.pdf"); await (await downloading).saveAs(file)
  const doc = await getDocument({ data: new Uint8Array(readFileSync(file)), isEvalSupported: false }).promise
  try {
    const attachment = (await doc.getAttachments())["resumezip.json"]
    const json = new TextDecoder().decode(attachment.content)
    expect(JSON.parse(json).version).toBe(2)
    expect(json).not.toContain("PRIVATE")
    const contents = await Promise.all(Array.from({ length: doc.numPages }, async (_, index) => (await doc.getPage(index + 1)).getTextContent()))
    const text = contents.flatMap((content) => content.items.map((item) => "str" in item ? item.str : "")).join(" ")
    expect(text).toContain("Certified Engineer")
    expect(text).toContain("Literal prose")
    expect(text).not.toContain("PRIVATE")
  } finally { await doc.destroy() }
  const elsewhere = await browser.newContext()
  const other = await elsewhere.newPage()
  await other.goto("/create/dashboard")
  await other.locator('input[type="file"]').setInputFiles(file)
  await expect(other).toHaveURL(/\/create\/new\/flexible$/)
  await previewShown(other)
  const reopened = await saved(other)
  expect(Object.keys(reopened.extraSections)).toHaveLength(4)
  expect(reopened.extraSections.certifications.entries).toHaveLength(1)
  expect(JSON.stringify(reopened)).not.toContain("PRIVATE")
  await elsewhere.close()
  await page.reload(); await previewShown(page)
  await nav(page).getByRole("button", { name: /^\d+ Summary$/ }).click()
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused()
  await page.getByRole("button", { name: "Cancel", exact: true }).press("Escape")
  await expect(page.getByRole("button", { name: "Delete section", exact: true })).toBeFocused()
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect(nav(page).locator('[aria-current="true"]')).toBeFocused()
  await expect.poll(async () => (await saved(page)).extraSections.summary).toBeUndefined()
  expect(errors).toEqual([])
})

test("extra-only checking targets original list lines and deletion restores focus in Check mode", async ({ page }) => {
  const sectionId = "11111111-1111-4111-8111-111111111111"
  await page.addInitScript(({ sectionId }) => localStorage.setItem("resume:flexible", JSON.stringify({ id: "flexible", resumeTitle: "Extra checks", profileSection: { fullName: "Ada Lovelace" }, extraSections: { [sectionId]: { kind: "list", heading: "Interests", bullets: "○ PRIVATE_SENTINEL\n• Wrote the the notes" } }, sectionOrder: [`extra:${sectionId}`] })), { sectionId })
  await page.goto("/create/new/flexible")
  await previewShown(page)
  await page.getByRole("tab", { name: /^Check/ }).click()
  const panel = page.getByRole("tabpanel", { name: /^Check/ })
  await expect(panel.getByRole("region", { name: "Resume score" })).not.toContainText("Not scored yet")
  const issue = panel.getByRole("button", { name: /“the” twice in a row/ })
  await expect(issue).toBeVisible()
  await issue.click()
  const field = page.getByRole("textbox", { name: "Bullet points", exact: true })
  await expect(field).toBeFocused()
  expect(await field.evaluate((element: HTMLTextAreaElement) => element.value.slice(element.selectionStart, element.selectionEnd))).toBe("Wrote the the notes")
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused()
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect(page.locator("main h1")).toBeFocused()
  await expect(issue).toBeHidden()
})

test.describe("touch", () => {
test.use({ hasTouch: true })
test("narrow flows keep the keyboard closed on add and allow literal text, inclusion and deletion", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await open(page)
  await add(page, "Text")
  await expect(page.getByRole("heading", { name: "New section", exact: true })).toBeVisible()
  await expect(page.getByRole("textbox", { name: "Text", exact: true })).not.toBeFocused()
  await page.getByRole("textbox", { name: "Text", exact: true }).fill("Narrow screen content.")
  await rename(page, "")
  await expect(page.getByRole("heading", { name: "New section", exact: true })).toBeVisible()
  await page.getByRole("checkbox", { name: "Include section in the PDF", exact: true }).uncheck()
  await expect.poll(async () => Object.values((await saved(page)).extraSections ?? {}).some((section: any) => section.leftOut)).toBe(true)
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused()
  await page.getByRole("button", { name: "Delete section", exact: true }).click()
  await expect.poll(async () => Object.keys((await saved(page)).extraSections)).toEqual([])
  expect(await seriousAccessibilityProblems(page, [".react-pdf__Page"])).toEqual([])
})
})
